from enum import Enum


class MarkerColor(Enum):
    All = "All"
    Blue = "Blue"
    Cyan = "Cyan"
    Green = "Green"
    Yellow = "Yellow"
    Red = "Red"
    Pink = "Pink"
    Purple = "Purple"
    Fuchsia = "Fuchsia"
    Rose = "Rose"
    Lavender = "Lavender"
    Sky = "Sky"
    Mint = "Mint"
    Lemon = "Lemon"
    Sand = "Sand"
    Cocoa = "Cocoa"
    Cream = "Cream"


class FlagColor(Enum):
    All = "All"
    Blue = "Blue"
    Cyan = "Cyan"
    Green = "Green"
    Yellow = "Yellow"
    Red = "Red"
    Pink = "Pink"
    Purple = "Purple"
    Fuchsia = "Fuchsia"
    Rose = "Rose"
    Lavender = "Lavender"
    Sky = "Sky"
    Mint = "Mint"
    Lemon = "Lemon"
    Sand = "Sand"
    Cocoa = "Cocoa"
    Cream = "Cream"


class ClipColor(Enum):
    Orange = "Orange"
    Apricot = "Apricot"
    Yellow = "Yellow"
    Lime = "Lime"
    Olive = "Olive"
    Green = "Green"
    Teal = "Teal"
    Navy = "Navy"
    Blue = "Blue"
    Purple = "Purple"
    Violet = "Violet"
    Pink = "Pink"
    Tan = "Tan"
    Beige = "Beige"
    Brown = "Brown"
    Chocolate = "Chocolate"